# Generated by Django 5.2.5 on 2025-10-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='source',
            field=models.CharField(choices=[('invoices', 'Invoices'), ('expenses', 'Expenses'), ('accounting', 'Accounting')], default='invoices', max_length=20),
        ),
    ]
